server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  port: 5001

spring:
  # H2
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# Logging
logging:
  level:
    org:
      hibernate: info