server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  port: 5002

spring:
  # H2
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# Logging
logging:
  level:
    org:
      hibernate: info

# Task
task:
  executor:
    core:
      pool:
        size: 15
    max:
      pool:
        size: 30
    queue:
      capacity: 60

# HLS
hls:
  file:
    path: E:\Data\HLS\

# FFmpeg
ffmpeg:
  check:
    interval:
      millis: 10000
  option:
    hls:
      time: 2
      list:
        size: 3
      flags: delete_segments
    start:
      number: 1

api:
  key: abc